# Generated by Django 6.0.3 on 2026-03-25 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("contact_no", models.CharField(max_length=15, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("subject", models.CharField(max_length=200, null=True)),
                ("message", models.CharField(max_length=5000, null=True)),
                ("messagedate", models.DateField(null=True)),
                ("isread", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("description", models.CharField(max_length=5000, null=True)),
                ("image", models.FileField(null=True, upload_to="")),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                ("shiftingloc", models.CharField(max_length=200, null=True)),
                ("briefitems", models.CharField(max_length=200, null=True)),
                ("items", models.CharField(max_length=5000, null=True)),
                ("professional", models.CharField(max_length=500, null=True)),
                ("requestdate", models.DateTimeField(null=True)),
                ("remarks", models.CharField(max_length=500, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("updatedate", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
