# Generated by Django 6.0.3 on 2026-04-23 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moverspackers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteuser",
            name="professional",
        ),
        migrations.RemoveField(
            model_name="siteuser",
            name="user",
        ),
        migrations.AddField(
            model_name="siteuser",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="siteuser",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="isread",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="messagedate",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="items",
            field=models.TextField(null=True),
        ),
    ]
