# Generated by Django 6.0.3 on 2026-04-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moverspackers",
            "0002_remove_siteuser_professional_remove_siteuser_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="shiftingdate",
            field=models.DateField(null=True),
        ),
    ]
