# Generated by Django 6.0.3 on 2026-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moverspackers", "0004_services_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="advance_paid",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteuser",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partial", "Partial"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="siteuser",
            name="total_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
