# Generated by Django 6.0.3 on 2026-05-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moverspackers",
            "0005_siteuser_advance_paid_siteuser_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moverspackers.services",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
